// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEZBuEvR_lLFU2Wqndd7DXj4OKrkf178w',
    appId: '1:101852566098:android:0bbfddcacd6502c8bb058b',
    messagingSenderId: '101852566098',
    projectId: 'saniye-abla',
    storageBucket: 'saniye-abla.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmu9b-DcxVSgrUyusg74_LCio308XcyI',
    appId: '1:101852566098:ios:db1229ad2258a9d1bb058b',
    messagingSenderId: '101852566098',
    projectId: 'saniye-abla',
    storageBucket: 'saniye-abla.firebasestorage.app',
    iosBundleId: 'com.example.dreamAppFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnINIkCWhdkhM4WpP8Baokk1DVwIjxwSk',
    appId: '1:101852566098:web:5413e6a8a37c7725bb058b',
    messagingSenderId: '101852566098',
    projectId: 'saniye-abla',
    authDomain: 'saniye-abla.firebaseapp.com',
    storageBucket: 'saniye-abla.firebasestorage.app',
    measurementId: 'G-VF7EERCPM3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmu9b-DcxVSgrUyusg74_LCio308XcyI',
    appId: '1:101852566098:ios:db1229ad2258a9d1bb058b',
    messagingSenderId: '101852566098',
    projectId: 'saniye-abla',
    storageBucket: 'saniye-abla.firebasestorage.app',
    iosBundleId: 'com.example.dreamAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnINIkCWhdkhM4WpP8Baokk1DVwIjxwSk',
    appId: '1:101852566098:web:135b46f86193e293bb058b',
    messagingSenderId: '101852566098',
    projectId: 'saniye-abla',
    authDomain: 'saniye-abla.firebaseapp.com',
    storageBucket: 'saniye-abla.firebasestorage.app',
    measurementId: 'G-MB1D2Y48XF',
  );

}